#ifndef PERSONAL_FIREWALL_MAIN
#define PERSONAL_FIREWALL_MAIN

#define FIREWALL_RULE_CLEAR         0
#define FIREWALL_RULE_ADD_IP        1
#define FIREWALL_RULE_ADD_PORT      2
#define FIREWALL_RULE_REMOVE_IP     3
#define FIREWALL_RULE_REMOVE_PORT   4
#define FIREWALL_RULE_ADD_SUBNET    5
#define FIREWALL_RULE_REMOVE_SUBNET 6

#define RULE_BANIP     0x00
#define RULE_BANPORT   0x01
#define RULE_BANSUBNET 0x02


#endif